/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package client.version;

import java.awt.Color;
import java.io.IOException;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author user
 */
public class Account_Info extends javax.swing.JFrame {

    /**
     * Creates new form Account_Info
     */
    public Account_Info() throws SQLException, IOException, ClassNotFoundException {
        initComponents();
        Vector info=new Vector();
        info=Logic.functions.getInfo(ClientVersion.b.getEmail());
        ID.setText(info.get(0).toString());
        NAME.setText(info.get(1).toString());
        MOBILE.setText(info.get(3).toString());
        WALLET1.setText(info.get(4).toString());
        EMAIL.setText(info.get(5).toString());
        ClientVersion.b.setWallet(Integer.valueOf(info.get(4).toString()));
        ACC_INFO.setForeground(Color.BLACK);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        MOBILE = new javax.swing.JLabel();
        EMAIL = new javax.swing.JLabel();
        NAME = new javax.swing.JLabel();
        ORDERS = new javax.swing.JLabel();
        WALLET = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        WALLET1 = new javax.swing.JLabel();
        COUNTRY2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        ID = new javax.swing.JLabel();
        ChangePASS = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        CART = new javax.swing.JLabel();
        BROWSER = new javax.swing.JLabel();
        LOGOUT = new javax.swing.JLabel();
        ACC_INFO = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel1.setText("Account information");

        jLabel8.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel8.setText("Email:");

        jLabel9.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel9.setText("Mobile:");

        jLabel3.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel3.setText("User name:");

        MOBILE.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        MOBILE.setText("here");

        EMAIL.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        EMAIL.setText("here");

        NAME.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        NAME.setText("here");

        ORDERS.setBackground(new java.awt.Color(255, 255, 255));
        ORDERS.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        ORDERS.setIcon(new javax.swing.ImageIcon("D:\\Market place system\\Client\\Icons\\Windows\\Square44x44Logo.targetsize-32.png")); // NOI18N
        ORDERS.setText("Orders");
        ORDERS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ORDERSMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ORDERSMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ORDERSMouseExited(evt);
            }
        });

        WALLET.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        WALLET.setIcon(new javax.swing.ImageIcon("D:\\Market place system\\Client\\Icons\\wallet\\Windows\\Square44x44Logo.targetsize-32.png")); // NOI18N
        WALLET.setText("Card to Wallet");
        WALLET.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                WALLETMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                WALLETMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                WALLETMouseExited(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel13.setText("Wallet amount:");

        WALLET1.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        WALLET1.setText("here");

        COUNTRY2.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        COUNTRY2.setText("EG");

        jLabel14.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel14.setText("User ID:");

        ID.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        ID.setText("here");

        ChangePASS.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        ChangePASS.setIcon(new javax.swing.ImageIcon("D:\\Market place system\\Client\\Icons\\ChangePassword.png")); // NOI18N
        ChangePASS.setText("Change Password");
        ChangePASS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ChangePASSMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ChangePASSMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ChangePASSMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(207, 207, 207)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(87, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(WALLET)
                    .addComponent(ORDERS)
                    .addComponent(jLabel9)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(WALLET1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(COUNTRY2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(62, 62, 62)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ID)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(EMAIL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(MOBILE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(NAME, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(ChangePASS))
                .addGap(94, 94, 94))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel1)
                .addGap(110, 110, 110)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(ID))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(NAME))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(EMAIL))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(MOBILE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(WALLET1)
                    .addComponent(COUNTRY2))
                .addGap(133, 133, 133)
                .addComponent(ORDERS)
                .addGap(18, 18, 18)
                .addComponent(WALLET)
                .addGap(18, 18, 18)
                .addComponent(ChangePASS)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(20, 214, 174));

        jLabel6.setIcon(new javax.swing.ImageIcon("D:\\Market place system\\Client\\Icons\\Capture-modified_180x180 (1).png")); // NOI18N
        jLabel6.setText("jLabel6");

        jLabel5.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel5.setText("Second walk clothes store");

        jLabel7.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel7.setText("Online store solution ");

        CART.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        CART.setForeground(new java.awt.Color(255, 255, 255));
        CART.setIcon(new javax.swing.ImageIcon("D:\\Market place system\\Client\\Icons\\Cart-03-modified_1_60x60.png")); // NOI18N
        CART.setText("Cart");
        CART.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CARTMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CARTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CARTMouseExited(evt);
            }
        });

        BROWSER.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        BROWSER.setForeground(new java.awt.Color(255, 255, 255));
        BROWSER.setIcon(new javax.swing.ImageIcon("D:\\Market place system\\Client\\Icons\\emyller-magnifying-glass-modified_60x60.png")); // NOI18N
        BROWSER.setText("Browser");
        BROWSER.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BROWSERMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BROWSERMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BROWSERMouseExited(evt);
            }
        });

        LOGOUT.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        LOGOUT.setForeground(new java.awt.Color(255, 255, 255));
        LOGOUT.setIcon(new javax.swing.ImageIcon("D:\\Market place system\\Client\\Icons\\LogOut.png")); // NOI18N
        LOGOUT.setText("Logout");
        LOGOUT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LOGOUTMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LOGOUTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LOGOUTMouseExited(evt);
            }
        });

        ACC_INFO.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        ACC_INFO.setForeground(new java.awt.Color(255, 255, 255));
        ACC_INFO.setIcon(new javax.swing.ImageIcon("D:\\Market place system\\Client\\Icons\\account info.png")); // NOI18N
        ACC_INFO.setText("Account info");
        ACC_INFO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ACC_INFOMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ACC_INFOMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ACC_INFOMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LOGOUT, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CART, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BROWSER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ACC_INFO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CART, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BROWSER, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(ACC_INFO, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LOGOUT, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ORDERSMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ORDERSMouseEntered
        ORDERS.setForeground(jPanel1.getBackground());

       

    }//GEN-LAST:event_ORDERSMouseEntered

    private void ORDERSMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ORDERSMouseExited
        ORDERS.setForeground(Color.BLACK);
    }//GEN-LAST:event_ORDERSMouseExited

    private void WALLETMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WALLETMouseEntered
        WALLET.setForeground(jPanel1.getBackground());

    }//GEN-LAST:event_WALLETMouseEntered

    private void WALLETMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WALLETMouseExited
        WALLET.setForeground(Color.BLACK);
    }//GEN-LAST:event_WALLETMouseExited

    private void WALLETMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WALLETMouseClicked
        new Wallet_Converter().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_WALLETMouseClicked

    private void CARTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CARTMouseClicked
        new Cart().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CARTMouseClicked

    private void CARTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CARTMouseEntered
        CART.setForeground(Color.BLACK);
    }//GEN-LAST:event_CARTMouseEntered

    private void CARTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CARTMouseExited
        CART.setForeground(Color.WHITE);
    }//GEN-LAST:event_CARTMouseExited

    private void BROWSERMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BROWSERMouseClicked
        new Browser().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BROWSERMouseClicked

    private void BROWSERMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BROWSERMouseEntered
        BROWSER.setForeground(Color.BLACK);
    }//GEN-LAST:event_BROWSERMouseEntered

    private void BROWSERMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BROWSERMouseExited
        BROWSER.setForeground(Color.WHITE);
    }//GEN-LAST:event_BROWSERMouseExited

    private void LOGOUTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LOGOUTMouseClicked
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LOGOUTMouseClicked

    private void LOGOUTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LOGOUTMouseEntered
        LOGOUT.setForeground(Color.BLACK);
    }//GEN-LAST:event_LOGOUTMouseEntered

    private void LOGOUTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LOGOUTMouseExited
        LOGOUT.setForeground(Color.WHITE);
    }//GEN-LAST:event_LOGOUTMouseExited

    private void ACC_INFOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ACC_INFOMouseClicked
        //new Account_Info().setVisible(true);
        //this.dispose();
    }//GEN-LAST:event_ACC_INFOMouseClicked

    private void ACC_INFOMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ACC_INFOMouseEntered
       // ACC_INFO.setForeground(Color.BLACK);
    }//GEN-LAST:event_ACC_INFOMouseEntered

    private void ACC_INFOMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ACC_INFOMouseExited
        //ACC_INFO.setForeground(Color.WHITE);
    }//GEN-LAST:event_ACC_INFOMouseExited

    private void ChangePASSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChangePASSMouseClicked
        new Change_Password().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ChangePASSMouseClicked

    private void ChangePASSMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChangePASSMouseEntered
        ChangePASS.setForeground(jPanel1.getBackground());
    }//GEN-LAST:event_ChangePASSMouseEntered

    private void ChangePASSMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChangePASSMouseExited
        ChangePASS.setForeground(Color.BLACK);
    }//GEN-LAST:event_ChangePASSMouseExited

    private void ORDERSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ORDERSMouseClicked
        try {
            new Orders().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Account_Info.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Account_Info.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Account_Info.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_ORDERSMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Account_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Account_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Account_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Account_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Account_Info().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Account_Info.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(Account_Info.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Account_Info.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ACC_INFO;
    private javax.swing.JLabel BROWSER;
    private javax.swing.JLabel CART;
    private javax.swing.JLabel COUNTRY2;
    private javax.swing.JLabel ChangePASS;
    private javax.swing.JLabel EMAIL;
    private javax.swing.JLabel ID;
    private javax.swing.JLabel LOGOUT;
    private javax.swing.JLabel MOBILE;
    private javax.swing.JLabel NAME;
    private javax.swing.JLabel ORDERS;
    private javax.swing.JLabel WALLET;
    private javax.swing.JLabel WALLET1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
