/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package client.version;
import java.awt.Color;
import java.io.IOException;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class Cart extends javax.swing.JFrame {

    /**
     * Creates new form Cart
     */
    public Cart() {
        initComponents();
        ClientVersion.b.TestAndSetItems();
        TOTAL.setText("0");
        Logic.functions.fill_Cart_table(jTable1, ClientVersion.b.getItems(), TOTAL);
        CART7.setForeground(Color.BLACK);
        QTY.setText("0");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        ADD = new javax.swing.JButton();
        Purchase = new javax.swing.JButton();
        EDIT = new javax.swing.JButton();
        REMOVE1 = new javax.swing.JButton();
        QTY = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TOTAL = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        REMOVE2 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        CART7 = new javax.swing.JLabel();
        BROWSER7 = new javax.swing.JLabel();
        LOGOUT7 = new javax.swing.JLabel();
        ACC_INFO7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(900, 700));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel1.setText("Cart");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item ID", "Item name", "Quantity", "price per unit"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setColumnSelectionAllowed(true);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        ADD.setBackground(new java.awt.Color(20, 214, 174));
        ADD.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        ADD.setText("+");
        ADD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ADDMouseClicked(evt);
            }
        });
        ADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADDActionPerformed(evt);
            }
        });

        Purchase.setBackground(new java.awt.Color(20, 214, 174));
        Purchase.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        Purchase.setText("Purchase");
        Purchase.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PurchaseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PurchaseMouseEntered(evt);
            }
        });

        EDIT.setBackground(new java.awt.Color(20, 214, 174));
        EDIT.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        EDIT.setText("Edit item");
        EDIT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EDITMouseClicked(evt);
            }
        });
        EDIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EDITActionPerformed(evt);
            }
        });

        REMOVE1.setBackground(new java.awt.Color(20, 214, 174));
        REMOVE1.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        REMOVE1.setText("-");
        REMOVE1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                REMOVE1MouseClicked(evt);
            }
        });
        REMOVE1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REMOVE1ActionPerformed(evt);
            }
        });

        QTY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QTYActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel2.setText("Total:");

        TOTAL.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        TOTAL.setText("1000");

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel4.setText("EG");

        REMOVE2.setBackground(new java.awt.Color(20, 214, 174));
        REMOVE2.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        REMOVE2.setText("Remove item");
        REMOVE2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                REMOVE2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(158, 158, 158))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(Purchase, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(195, 195, 195))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(REMOVE1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EDIT)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(TOTAL, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel4))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(QTY, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ADD)
                                    .addGap(240, 240, 240))
                                .addComponent(REMOVE2)))))
                .addGap(0, 68, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(REMOVE2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TOTAL)
                                    .addComponent(jLabel4))
                                .addGap(28, 28, 28)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(QTY)
                                    .addComponent(REMOVE1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(ADD, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(EDIT, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Purchase)
                .addGap(20, 20, 20))
        );

        jPanel6.setBackground(new java.awt.Color(20, 214, 174));

        jLabel19.setIcon(new javax.swing.ImageIcon("D:\\Market place system\\Client\\Icons\\Capture-modified_180x180 (1).png")); // NOI18N
        jLabel19.setText("jLabel6");

        jLabel20.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel20.setText("Second walk clothes store");

        jLabel21.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel21.setText("Online store solution ");

        CART7.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        CART7.setForeground(new java.awt.Color(255, 255, 255));
        CART7.setIcon(new javax.swing.ImageIcon("D:\\Market place system\\Client\\Icons\\Cart-03-modified_1_60x60.png")); // NOI18N
        CART7.setText("Cart");
        CART7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CART7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CART7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CART7MouseExited(evt);
            }
        });

        BROWSER7.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        BROWSER7.setForeground(new java.awt.Color(255, 255, 255));
        BROWSER7.setIcon(new javax.swing.ImageIcon("D:\\Market place system\\Client\\Icons\\emyller-magnifying-glass-modified_60x60.png")); // NOI18N
        BROWSER7.setText("Browser");
        BROWSER7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BROWSER7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BROWSER7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BROWSER7MouseExited(evt);
            }
        });

        LOGOUT7.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        LOGOUT7.setForeground(new java.awt.Color(255, 255, 255));
        LOGOUT7.setIcon(new javax.swing.ImageIcon("D:\\Market place system\\Client\\Icons\\LogOut.png")); // NOI18N
        LOGOUT7.setText("Logout");
        LOGOUT7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LOGOUT7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LOGOUT7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LOGOUT7MouseExited(evt);
            }
        });

        ACC_INFO7.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        ACC_INFO7.setForeground(new java.awt.Color(255, 255, 255));
        ACC_INFO7.setIcon(new javax.swing.ImageIcon("D:\\Market place system\\Client\\Icons\\account info.png")); // NOI18N
        ACC_INFO7.setText("Account info");
        ACC_INFO7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ACC_INFO7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ACC_INFO7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ACC_INFO7MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LOGOUT7, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CART7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BROWSER7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ACC_INFO7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel19)
                .addGap(18, 18, 18)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CART7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BROWSER7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(ACC_INFO7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LOGOUT7, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void REMOVE1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REMOVE1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_REMOVE1ActionPerformed

    private void ADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ADDActionPerformed

    private void QTYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QTYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QTYActionPerformed

    private void CART7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CART7MouseClicked
//        new Cart().setVisible(true);
//        this.dispose();
    }//GEN-LAST:event_CART7MouseClicked

    private void CART7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CART7MouseEntered
//        CART7.setForeground(Color.BLACK);
    }//GEN-LAST:event_CART7MouseEntered

    private void CART7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CART7MouseExited
        //CART7.setForeground(Color.WHITE);
    }//GEN-LAST:event_CART7MouseExited

    private void BROWSER7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BROWSER7MouseClicked
        new Browser().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BROWSER7MouseClicked

    private void BROWSER7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BROWSER7MouseEntered
        BROWSER7.setForeground(Color.BLACK);
    }//GEN-LAST:event_BROWSER7MouseEntered

    private void BROWSER7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BROWSER7MouseExited
        BROWSER7.setForeground(Color.WHITE);
    }//GEN-LAST:event_BROWSER7MouseExited

    private void LOGOUT7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LOGOUT7MouseClicked
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LOGOUT7MouseClicked

    private void LOGOUT7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LOGOUT7MouseEntered
        LOGOUT7.setForeground(Color.BLACK);
    }//GEN-LAST:event_LOGOUT7MouseEntered

    private void LOGOUT7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LOGOUT7MouseExited
        LOGOUT7.setForeground(Color.WHITE);
    }//GEN-LAST:event_LOGOUT7MouseExited

    private void ACC_INFO7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ACC_INFO7MouseClicked
        try {
            new Account_Info().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Cart.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Cart.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Cart.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_ACC_INFO7MouseClicked

    private void ACC_INFO7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ACC_INFO7MouseEntered
        ACC_INFO7.setForeground(Color.BLACK);
    }//GEN-LAST:event_ACC_INFO7MouseEntered

    private void ACC_INFO7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ACC_INFO7MouseExited
        ACC_INFO7.setForeground(Color.WHITE);
    }//GEN-LAST:event_ACC_INFO7MouseExited

    private void PurchaseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PurchaseMouseClicked
        try {
            int valid=Logic.functions.Purchase(ClientVersion.b.getItems(),TOTAL.getText());
            if(valid==1)
            {
                Vector temp=Logic.functions.getInfo(ClientVersion.b.getEmail());
                ClientVersion.b.setWallet(Integer.valueOf(temp.get(4).toString()));
                
                GmailAPI.sendMail(ClientVersion.b.getEmail(),"ORDER CONFIRMATION","Thanks for shopping with us!"+"\n"+Logic.functions.Reciept());
                new CheckOut_Form().setVisible(true);
                
                this.dispose();
                

                
            }
                            else if(valid==-1)
                    JOptionPane.showMessageDialog(this, "Insuffiecient balance");
            else
            {
                Logic.functions.fill_Cart_table(jTable1, ClientVersion.b.getItems(), TOTAL);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Cart.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Cart.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Cart.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(Cart.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_PurchaseMouseClicked

    private void EDITMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EDITMouseClicked
        if(Integer.valueOf( QTY.getText())>Logic.functions.getMaxAmountItem(jTable1, ClientVersion.b.getItems()))
        {
            QTY.setText("100");
        }
        Logic.functions.Manipulate_Cart(jTable1, QTY,TOTAL);
        Logic.functions.Refresh_Cart(jTable1,  ClientVersion.b.getItems(), TOTAL);
    }//GEN-LAST:event_EDITMouseClicked

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed

    }//GEN-LAST:event_jTable1KeyPressed

    private void ADDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ADDMouseClicked
        if(QTY.getText().isEmpty())
        {
            QTY.setText("0");
        }
        int max=Logic.functions.getMaxAmountItem(jTable1, ClientVersion.b.getItems());
        int qty=(Integer.valueOf(QTY.getText()));
        if(qty+1<=max)
        {
            QTY.setText( String.valueOf((Integer.valueOf(QTY.getText())+1)));
            REMOVE1.setBackground(jPanel6.getBackground());
        }
        else
        {
            ADD.setBackground(Color.white);
        }
    }//GEN-LAST:event_ADDMouseClicked

    private void REMOVE1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_REMOVE1MouseClicked
        if(QTY.getText().isEmpty())
        {
            QTY.setText("0");
        }
        if(Integer.valueOf(QTY.getText())>0)
        {
            QTY.setText( String.valueOf((Integer.valueOf(QTY.getText())-1)));
            REMOVE1.setBackground(jPanel6.getBackground());
            ADD.setBackground(jPanel6.getBackground());
            if(Integer.valueOf(QTY.getText())==0)
            {
                REMOVE1.setBackground(Color.white);
                
            }
        }
        else
        {
            REMOVE1.setBackground(Color.white);
        }
    }//GEN-LAST:event_REMOVE1MouseClicked

    private void REMOVE2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_REMOVE2MouseClicked
        Logic.functions.Remove_from_cart(jTable1);
        Logic.functions.Refresh_Cart(jTable1,  ClientVersion.b.getItems(), TOTAL);
    }//GEN-LAST:event_REMOVE2MouseClicked

    private void EDITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EDITActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EDITActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        DefaultTableModel model=(DefaultTableModel)jTable1.getModel(); 
        int row = jTable1.getSelectedRow();
         
         QTY.setText(model.getValueAt(row, 2).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void PurchaseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PurchaseMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_PurchaseMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cart().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ACC_INFO7;
    private javax.swing.JButton ADD;
    private javax.swing.JLabel BROWSER7;
    private javax.swing.JLabel CART7;
    private javax.swing.JButton EDIT;
    private javax.swing.JLabel LOGOUT7;
    private javax.swing.JButton Purchase;
    private javax.swing.JTextField QTY;
    private javax.swing.JButton REMOVE1;
    private javax.swing.JButton REMOVE2;
    private javax.swing.JLabel TOTAL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
