/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package client.version;
import java.awt.Color;
import java.io.IOException;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.border.Border;
import javax.swing.border.EtchedBorder;
import javax.swing.table.DefaultTableModel;
import classes.*;
import java.awt.Component;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author user
 */
public class Clothes_browser extends javax.swing.JFrame {

    private Border EtchedBorder;

    /**
     * Creates new form Clothes_browser
     */
    public Clothes_browser() throws SQLException, IOException, ClassNotFoundException, InterruptedException {
        initComponents();
  
    String[] columns={"Item ID","Item name","category","gender","color","size","price","Image"};
    Object[][] rows={};
    DefaultTableModel model = new DefaultTableModel(rows, columns) {
    @Override
    public Class<?> getColumnClass(int column) {
        switch(column) {
            case 0:
            case 1: return Integer.class;
            case 7: return ImageIcon.class;
            default: return Object.class;
        }
    }
   
};
        
        
        
        
        
        
        jTable1.setModel(model);
        jTable1.setRowHeight(80);
        TableColumnModel columnModel = jTable1.getColumnModel();
        columnModel.getColumn(7).setWidth(80);
        
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment( JLabel.CENTER );
        jTable1.getColumnModel().getColumn(0).setCellRenderer( centerRenderer );
        jTable1.getColumnModel().getColumn(1).setCellRenderer( centerRenderer );
        jTable1.getColumnModel().getColumn(2).setCellRenderer( centerRenderer );
        jTable1.getColumnModel().getColumn(3).setCellRenderer( centerRenderer );
        jTable1.getColumnModel().getColumn(4).setCellRenderer( centerRenderer );
        jTable1.getColumnModel().getColumn(5).setCellRenderer( centerRenderer );
        jTable1.getColumnModel().getColumn(6).setCellRenderer( centerRenderer );
        
        
        Logic.functions.RetrieveClothes();
        
        Logic.functions.RetrieveClothesIcon();
        Logic.functions.fill_clothes_table(jTable1 ,ClientVersion.b.getClothe());
        
        QTY.setText("0");
        
        
    }


    
//                public class  tablek implements TableCellRenderer{
//                    public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column){
//                    table.setRowHeight(70);
//                    return (Component)value;
//                }
//                }

    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        ADD = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        REMOVE = new javax.swing.JButton();
        QTY = new javax.swing.JTextField();
        SEARCHBAR = new javax.swing.JTextField();
        SEARCH_BTN = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        CART7 = new javax.swing.JLabel();
        BROWSER7 = new javax.swing.JLabel();
        LOGOUT7 = new javax.swing.JLabel();
        ACC_INFO7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel1.setText("Clothes browser");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item ID", "Item name", "Category", "Gender", "Color", "size", "price", "Image"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(7).setCellRenderer(new MyRender());
        }

        ADD.setBackground(new java.awt.Color(20, 214, 174));
        ADD.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        ADD.setText("+");
        ADD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ADDMouseClicked(evt);
            }
        });
        ADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADDActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(20, 214, 174));
        jButton2.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jButton2.setText("Add to cart");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        REMOVE.setBackground(new java.awt.Color(20, 214, 174));
        REMOVE.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        REMOVE.setText("-");
        REMOVE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                REMOVEMouseClicked(evt);
            }
        });
        REMOVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REMOVEActionPerformed(evt);
            }
        });

        QTY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QTYActionPerformed(evt);
            }
        });
        QTY.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                QTYKeyTyped(evt);
            }
        });

        SEARCHBAR.setText("Search");
        SEARCHBAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SEARCHBARActionPerformed(evt);
            }
        });

        SEARCH_BTN.setBackground(new java.awt.Color(255, 204, 51));
        SEARCH_BTN.setIcon(new javax.swing.ImageIcon("D:\\Market place system\\Client\\Icons\\search.png")); // NOI18N
        SEARCH_BTN.setBorder(null);
        SEARCH_BTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SEARCH_BTNMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SEARCH_BTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SEARCH_BTNMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(REMOVE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(QTY, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ADD)
                .addGap(279, 279, 279)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(SEARCHBAR, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SEARCH_BTN))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SEARCH_BTN, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SEARCHBAR, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(QTY)
                            .addComponent(REMOVE, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addComponent(ADD, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(87, 87, 87))
        );

        jPanel6.setBackground(new java.awt.Color(20, 214, 174));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/icons/Capture-modified_180x180 (1).png"))); // NOI18N
        jLabel19.setText("jLabel6");

        jLabel20.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel20.setText("Second walk clothes store");

        jLabel21.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel21.setText("Online store solution ");

        CART7.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        CART7.setForeground(new java.awt.Color(255, 255, 255));
        CART7.setIcon(new javax.swing.ImageIcon("D:\\Market place system\\Client\\Icons\\Cart-03-modified_1_60x60.png")); // NOI18N
        CART7.setText("Cart");
        CART7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CART7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CART7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CART7MouseExited(evt);
            }
        });

        BROWSER7.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        BROWSER7.setForeground(new java.awt.Color(255, 255, 255));
        BROWSER7.setIcon(new javax.swing.ImageIcon("D:\\Market place system\\Client\\Icons\\emyller-magnifying-glass-modified_60x60.png")); // NOI18N
        BROWSER7.setText("Browser");
        BROWSER7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BROWSER7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BROWSER7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BROWSER7MouseExited(evt);
            }
        });

        LOGOUT7.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        LOGOUT7.setForeground(new java.awt.Color(255, 255, 255));
        LOGOUT7.setIcon(new javax.swing.ImageIcon("D:\\Market place system\\Client\\Icons\\LogOut.png")); // NOI18N
        LOGOUT7.setText("Logout");
        LOGOUT7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LOGOUT7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LOGOUT7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LOGOUT7MouseExited(evt);
            }
        });

        ACC_INFO7.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        ACC_INFO7.setForeground(new java.awt.Color(255, 255, 255));
        ACC_INFO7.setIcon(new javax.swing.ImageIcon("D:\\Market place system\\Client\\Icons\\account info.png")); // NOI18N
        ACC_INFO7.setText("Account info");
        ACC_INFO7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ACC_INFO7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ACC_INFO7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ACC_INFO7MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LOGOUT7, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CART7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BROWSER7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ACC_INFO7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel19)
                .addGap(18, 18, 18)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CART7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BROWSER7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(ACC_INFO7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LOGOUT7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ADDActionPerformed

    private void REMOVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REMOVEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_REMOVEActionPerformed

    private void QTYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QTYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QTYActionPerformed

    private void SEARCHBARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SEARCHBARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SEARCHBARActionPerformed

    private void CART7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CART7MouseClicked
                new Cart().setVisible(true);
                this.dispose();
    }//GEN-LAST:event_CART7MouseClicked

    private void CART7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CART7MouseEntered
                CART7.setForeground(Color.BLACK);
    }//GEN-LAST:event_CART7MouseEntered

    private void CART7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CART7MouseExited
        CART7.setForeground(Color.WHITE);
    }//GEN-LAST:event_CART7MouseExited

    private void BROWSER7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BROWSER7MouseClicked
        new Browser().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BROWSER7MouseClicked

    private void BROWSER7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BROWSER7MouseEntered
        BROWSER7.setForeground(Color.BLACK);
    }//GEN-LAST:event_BROWSER7MouseEntered

    private void BROWSER7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BROWSER7MouseExited
        BROWSER7.setForeground(Color.WHITE);
    }//GEN-LAST:event_BROWSER7MouseExited

    private void LOGOUT7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LOGOUT7MouseClicked
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LOGOUT7MouseClicked

    private void LOGOUT7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LOGOUT7MouseEntered
        LOGOUT7.setForeground(Color.BLACK);
    }//GEN-LAST:event_LOGOUT7MouseEntered

    private void LOGOUT7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LOGOUT7MouseExited
        LOGOUT7.setForeground(Color.WHITE);
    }//GEN-LAST:event_LOGOUT7MouseExited

    private void ACC_INFO7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ACC_INFO7MouseClicked
        try {
            new Account_Info().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Clothes_browser.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Clothes_browser.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Clothes_browser.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_ACC_INFO7MouseClicked

    private void ACC_INFO7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ACC_INFO7MouseEntered
        ACC_INFO7.setForeground(Color.BLACK);
    }//GEN-LAST:event_ACC_INFO7MouseEntered

    private void ACC_INFO7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ACC_INFO7MouseExited
        ACC_INFO7.setForeground(Color.WHITE);
    }//GEN-LAST:event_ACC_INFO7MouseExited

    private void SEARCH_BTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SEARCH_BTNMouseEntered
            
            SEARCH_BTN.setBorder(BorderFactory.createLineBorder(Color.GREEN));
    }//GEN-LAST:event_SEARCH_BTNMouseEntered

    private void SEARCH_BTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SEARCH_BTNMouseExited
            SEARCH_BTN.setBorder(BorderFactory.createLineBorder(Color.WHITE));
    }//GEN-LAST:event_SEARCH_BTNMouseExited

    private void SEARCH_BTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SEARCH_BTNMouseClicked
        try {
            Logic.functions.RetrieveClothes();
            Logic.functions.RetrieveClothesIcon();
            Logic.functions.Search_in_Clothes(jTable1, ClientVersion.b.getClothe(), SEARCHBAR.getText());
        } catch (SQLException ex) {
            Logger.getLogger(Clothes_browser.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Clothes_browser.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Clothes_browser.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InterruptedException ex) {
            Logger.getLogger(Clothes_browser.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_SEARCH_BTNMouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        Logic.functions.added_items_clth(jTable1, QTY);
    }//GEN-LAST:event_jButton2MouseClicked

    private void ADDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ADDMouseClicked
        if(QTY.getText().isEmpty())
        {
            QTY.setText("0");
        }
        int max=Logic.functions.getMaxAmountCloth(jTable1, ClientVersion.b.getClothe());
        int qty=(Integer.valueOf(QTY.getText()));
        if(qty+1<=max)
        {
            QTY.setText( String.valueOf((Integer.valueOf(QTY.getText().replaceAll(" ", ""))+1)));
            REMOVE.setBackground(jPanel6.getBackground());
        }
        else
        {
            ADD.setBackground(Color.white);
        }
    }//GEN-LAST:event_ADDMouseClicked

    private void REMOVEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_REMOVEMouseClicked
        if(QTY.getText().isEmpty())
        {
            QTY.setText("0");
        }
        if(Integer.valueOf(QTY.getText())>0)
        {
            QTY.setText( String.valueOf((Integer.valueOf(QTY.getText().replaceAll(" ",""))-1)));
            REMOVE.setBackground(jPanel6.getBackground());
            ADD.setBackground(jPanel6.getBackground());
            if(Integer.valueOf(QTY.getText())==0)
            {
                REMOVE.setBackground(Color.white);
            }
        }
        else
        {
            REMOVE.setBackground(Color.white);
        }
    }//GEN-LAST:event_REMOVEMouseClicked

    private void QTYKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_QTYKeyTyped
        if(Integer.valueOf( QTY.getText().replaceAll(" ", ""))>Logic.functions.getMaxAmountCloth(jTable1, ClientVersion.b.getClothe()))
        {
            QTY.setText("100");
        }
        else
        {
             QTY.setText(QTY.getText());
        }

    }//GEN-LAST:event_QTYKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Clothes_browser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Clothes_browser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Clothes_browser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Clothes_browser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Clothes_browser().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Clothes_browser.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(Clothes_browser.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Clothes_browser.class.getName()).log(Level.SEVERE, null, ex);
                } catch (InterruptedException ex) {
                    Logger.getLogger(Clothes_browser.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ACC_INFO7;
    private javax.swing.JButton ADD;
    private javax.swing.JLabel BROWSER7;
    private javax.swing.JLabel CART7;
    private javax.swing.JLabel LOGOUT7;
    private javax.swing.JTextField QTY;
    private javax.swing.JButton REMOVE;
    private javax.swing.JTextField SEARCHBAR;
    private javax.swing.JLabel SEARCH_BTN;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
