/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package client.version;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.border.Border;
import javax.swing.border.EtchedBorder;
/**
 *
 * @author user
 */
public class Clothes_browser extends javax.swing.JFrame {

    private Border EtchedBorder;

    /**
     * Creates new form Clothes_browser
     */
    public Clothes_browser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        SEARCHBAR = new javax.swing.JTextField();
        SEARCH_BTN = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        CART7 = new javax.swing.JLabel();
        BROWSER7 = new javax.swing.JLabel();
        LOGOUT7 = new javax.swing.JLabel();
        ACC_INFO7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel1.setText("Clothes browser");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"11", "pant ea", "clothes ", "3", null, "321"},
                {"22", "shirt soo", "clothes", "4", null, "12"},
                {"33", "nestle water", "consumables", "5", null, "23"},
                {"44", "oil ", "consumables", "1", null, "44"}
            },
            new String [] {
                "Item ID", "Item name", "Category", "Quantity", "Description", "price per unit"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setBackground(new java.awt.Color(20, 214, 174));
        jButton1.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        jButton1.setText("+");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(20, 214, 174));
        jButton2.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jButton2.setText("Add to cart");

        jButton6.setBackground(new java.awt.Color(20, 214, 174));
        jButton6.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        jButton6.setText("-");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        SEARCHBAR.setText("Search");
        SEARCHBAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SEARCHBARActionPerformed(evt);
            }
        });

        SEARCH_BTN.setBackground(new java.awt.Color(255, 204, 51));
        SEARCH_BTN.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\OneDrive\\Desktop\\121.png")); // NOI18N
        SEARCH_BTN.setBorder(null);
        SEARCH_BTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SEARCH_BTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SEARCH_BTNMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(SEARCHBAR, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SEARCH_BTN)))
                .addGap(65, 65, 65))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SEARCH_BTN, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SEARCHBAR, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(87, 87, 87))
        );

        jPanel6.setBackground(new java.awt.Color(20, 214, 174));

        jLabel19.setIcon(new javax.swing.ImageIcon("D:\\Market place system\\Client\\Icons\\Capture-modified_180x180 (1).png")); // NOI18N
        jLabel19.setText("jLabel6");

        jLabel20.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel20.setText("Second walk clothes store");

        jLabel21.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel21.setText("Online store solution ");

        CART7.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        CART7.setForeground(new java.awt.Color(255, 255, 255));
        CART7.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\OneDrive\\Desktop\\Cart-03-modified_1_60x60.png")); // NOI18N
        CART7.setText("Cart");
        CART7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CART7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CART7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CART7MouseExited(evt);
            }
        });

        BROWSER7.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        BROWSER7.setForeground(new java.awt.Color(255, 255, 255));
        BROWSER7.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\OneDrive\\Desktop\\emyller-magnifying-glass-modified_60x60.png")); // NOI18N
        BROWSER7.setText("Browser");
        BROWSER7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BROWSER7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BROWSER7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BROWSER7MouseExited(evt);
            }
        });

        LOGOUT7.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        LOGOUT7.setForeground(new java.awt.Color(255, 255, 255));
        LOGOUT7.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\OneDrive\\Desktop\\download-modified_60x60.png")); // NOI18N
        LOGOUT7.setText("Logout");
        LOGOUT7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LOGOUT7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LOGOUT7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LOGOUT7MouseExited(evt);
            }
        });

        ACC_INFO7.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        ACC_INFO7.setForeground(new java.awt.Color(255, 255, 255));
        ACC_INFO7.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\OneDrive\\Desktop\\Screenshot_2022-06-21_013532-modified_60x60.png")); // NOI18N
        ACC_INFO7.setText("Account info");
        ACC_INFO7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ACC_INFO7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ACC_INFO7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ACC_INFO7MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LOGOUT7, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CART7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BROWSER7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ACC_INFO7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel19)
                .addGap(18, 18, 18)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CART7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BROWSER7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(ACC_INFO7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LOGOUT7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void SEARCHBARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SEARCHBARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SEARCHBARActionPerformed

    private void CART7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CART7MouseClicked
                new Cart().setVisible(true);
                this.dispose();
    }//GEN-LAST:event_CART7MouseClicked

    private void CART7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CART7MouseEntered
                CART7.setForeground(Color.BLACK);
    }//GEN-LAST:event_CART7MouseEntered

    private void CART7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CART7MouseExited
        CART7.setForeground(Color.WHITE);
    }//GEN-LAST:event_CART7MouseExited

    private void BROWSER7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BROWSER7MouseClicked
        new Browser().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BROWSER7MouseClicked

    private void BROWSER7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BROWSER7MouseEntered
        BROWSER7.setForeground(Color.BLACK);
    }//GEN-LAST:event_BROWSER7MouseEntered

    private void BROWSER7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BROWSER7MouseExited
        BROWSER7.setForeground(Color.WHITE);
    }//GEN-LAST:event_BROWSER7MouseExited

    private void LOGOUT7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LOGOUT7MouseClicked
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LOGOUT7MouseClicked

    private void LOGOUT7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LOGOUT7MouseEntered
        LOGOUT7.setForeground(Color.BLACK);
    }//GEN-LAST:event_LOGOUT7MouseEntered

    private void LOGOUT7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LOGOUT7MouseExited
        LOGOUT7.setForeground(Color.WHITE);
    }//GEN-LAST:event_LOGOUT7MouseExited

    private void ACC_INFO7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ACC_INFO7MouseClicked
        new Account_Info().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ACC_INFO7MouseClicked

    private void ACC_INFO7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ACC_INFO7MouseEntered
        ACC_INFO7.setForeground(Color.BLACK);
    }//GEN-LAST:event_ACC_INFO7MouseEntered

    private void ACC_INFO7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ACC_INFO7MouseExited
        ACC_INFO7.setForeground(Color.WHITE);
    }//GEN-LAST:event_ACC_INFO7MouseExited

    private void SEARCH_BTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SEARCH_BTNMouseEntered
            
            SEARCH_BTN.setBorder(BorderFactory.createLineBorder(Color.GREEN));
    }//GEN-LAST:event_SEARCH_BTNMouseEntered

    private void SEARCH_BTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SEARCH_BTNMouseExited
            SEARCH_BTN.setBorder(BorderFactory.createLineBorder(Color.WHITE));
    }//GEN-LAST:event_SEARCH_BTNMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Clothes_browser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Clothes_browser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Clothes_browser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Clothes_browser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Clothes_browser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ACC_INFO7;
    private javax.swing.JLabel BROWSER7;
    private javax.swing.JLabel CART7;
    private javax.swing.JLabel LOGOUT7;
    private javax.swing.JTextField SEARCHBAR;
    private javax.swing.JLabel SEARCH_BTN;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
