/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package client.version;
import java.awt.Color;
/**
 *
 * @author user
 */
import java.awt.Color;
public class Wallet_Converter extends javax.swing.JFrame {

    /**
     * Creates new form Wallet_Converter
     */
    public Wallet_Converter() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        CARDNUMBER_FLD = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        CONFIRM_FLD = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        EXPIRATION_FLD = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        CVV_FLD = new javax.swing.JTextField();
        NAME_FLD = new javax.swing.JTextField();
        DEPOSITE_FLD = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        CART7 = new javax.swing.JLabel();
        BROWSER7 = new javax.swing.JLabel();
        LOGOUT7 = new javax.swing.JLabel();
        ACC_INFO7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel1.setText("Card to E-Wallet");

        jLabel2.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel2.setText("Card number");

        jLabel3.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel3.setText("Name on card");

        CONFIRM_FLD.setBackground(new java.awt.Color(20, 214, 174));
        CONFIRM_FLD.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        CONFIRM_FLD.setText("Confirm");
        CONFIRM_FLD.setBorderPainted(false);
        CONFIRM_FLD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CONFIRM_FLDMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel4.setText("Deposite amount");

        jLabel8.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel8.setText("Expiration");

        EXPIRATION_FLD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                EXPIRATION_FLDKeyTyped(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel9.setText("CVC/CVV");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(110, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(183, 183, 183))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(75, 75, 75)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(CONFIRM_FLD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4)
                            .addComponent(CARDNUMBER_FLD)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(NAME_FLD)
                            .addComponent(DEPOSITE_FLD, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(EXPIRATION_FLD, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CVV_FLD, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(85, 85, 85))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel1)
                .addGap(76, 76, 76)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CARDNUMBER_FLD, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EXPIRATION_FLD, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CVV_FLD, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(NAME_FLD, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(DEPOSITE_FLD, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(CONFIRM_FLD, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(128, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(20, 214, 174));

        jLabel19.setIcon(new javax.swing.ImageIcon("D:\\Market place system\\Client\\Icons\\Capture-modified_180x180 (1).png")); // NOI18N
        jLabel19.setText("jLabel6");

        jLabel20.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel20.setText("Second walk clothes store");

        jLabel21.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel21.setText("Online store solution ");

        CART7.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        CART7.setForeground(new java.awt.Color(255, 255, 255));
        CART7.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\OneDrive\\Desktop\\Cart-03-modified_1_60x60.png")); // NOI18N
        CART7.setText("Cart");
        CART7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CART7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CART7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CART7MouseExited(evt);
            }
        });

        BROWSER7.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        BROWSER7.setForeground(new java.awt.Color(255, 255, 255));
        BROWSER7.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\OneDrive\\Desktop\\emyller-magnifying-glass-modified_60x60.png")); // NOI18N
        BROWSER7.setText("Browser");
        BROWSER7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BROWSER7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BROWSER7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BROWSER7MouseExited(evt);
            }
        });

        LOGOUT7.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        LOGOUT7.setForeground(new java.awt.Color(255, 255, 255));
        LOGOUT7.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\OneDrive\\Desktop\\download-modified_60x60.png")); // NOI18N
        LOGOUT7.setText("Logout");
        LOGOUT7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LOGOUT7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LOGOUT7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LOGOUT7MouseExited(evt);
            }
        });

        ACC_INFO7.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        ACC_INFO7.setForeground(new java.awt.Color(255, 255, 255));
        ACC_INFO7.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\OneDrive\\Desktop\\Screenshot_2022-06-21_013532-modified_60x60.png")); // NOI18N
        ACC_INFO7.setText("Account info");
        ACC_INFO7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ACC_INFO7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ACC_INFO7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ACC_INFO7MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LOGOUT7, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CART7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BROWSER7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ACC_INFO7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel19)
                .addGap(18, 18, 18)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CART7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BROWSER7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(ACC_INFO7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LOGOUT7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CONFIRM_FLDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CONFIRM_FLDMouseClicked
        new Account_Info().setVisible(true);
        this.dispose();
        

    }//GEN-LAST:event_CONFIRM_FLDMouseClicked

    private void EXPIRATION_FLDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EXPIRATION_FLDKeyTyped
        
    }//GEN-LAST:event_EXPIRATION_FLDKeyTyped

    private void CART7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CART7MouseEntered
        CART7.setForeground(Color.BLACK);
    }//GEN-LAST:event_CART7MouseEntered

    private void CART7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CART7MouseExited
        CART7.setForeground(Color.WHITE);
    }//GEN-LAST:event_CART7MouseExited

    private void CART7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CART7MouseClicked
        new Cart().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CART7MouseClicked

    private void BROWSER7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BROWSER7MouseEntered
        BROWSER7.setForeground(Color.BLACK);
    }//GEN-LAST:event_BROWSER7MouseEntered

    private void BROWSER7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BROWSER7MouseExited
        BROWSER7.setForeground(Color.WHITE);
    }//GEN-LAST:event_BROWSER7MouseExited

    private void BROWSER7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BROWSER7MouseClicked
        new Browser().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BROWSER7MouseClicked

    private void ACC_INFO7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ACC_INFO7MouseEntered
        ACC_INFO7.setForeground(Color.BLACK);
    }//GEN-LAST:event_ACC_INFO7MouseEntered

    private void ACC_INFO7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ACC_INFO7MouseExited
        ACC_INFO7.setForeground(Color.WHITE);
    }//GEN-LAST:event_ACC_INFO7MouseExited

    private void ACC_INFO7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ACC_INFO7MouseClicked
        new Account_Info().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ACC_INFO7MouseClicked

    private void LOGOUT7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LOGOUT7MouseEntered
        LOGOUT7.setForeground(Color.BLACK);
    }//GEN-LAST:event_LOGOUT7MouseEntered

    private void LOGOUT7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LOGOUT7MouseExited
        LOGOUT7.setForeground(Color.WHITE);
    }//GEN-LAST:event_LOGOUT7MouseExited

    private void LOGOUT7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LOGOUT7MouseClicked
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LOGOUT7MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Wallet_Converter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Wallet_Converter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Wallet_Converter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Wallet_Converter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Wallet_Converter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ACC_INFO;
    private javax.swing.JLabel ACC_INFO1;
    private javax.swing.JLabel ACC_INFO2;
    private javax.swing.JLabel ACC_INFO3;
    private javax.swing.JLabel ACC_INFO4;
    private javax.swing.JLabel ACC_INFO5;
    private javax.swing.JLabel ACC_INFO6;
    private javax.swing.JLabel ACC_INFO7;
    private javax.swing.JLabel BROWSER;
    private javax.swing.JLabel BROWSER1;
    private javax.swing.JLabel BROWSER2;
    private javax.swing.JLabel BROWSER3;
    private javax.swing.JLabel BROWSER4;
    private javax.swing.JLabel BROWSER5;
    private javax.swing.JLabel BROWSER6;
    private javax.swing.JLabel BROWSER7;
    private javax.swing.JTextField CARDNUMBER_FLD;
    private javax.swing.JLabel CART;
    private javax.swing.JLabel CART1;
    private javax.swing.JLabel CART2;
    private javax.swing.JLabel CART3;
    private javax.swing.JLabel CART4;
    private javax.swing.JLabel CART5;
    private javax.swing.JLabel CART6;
    private javax.swing.JLabel CART7;
    private javax.swing.JButton CONFIRM_FLD;
    private javax.swing.JTextField CVV_FLD;
    private javax.swing.JTextField DEPOSITE_FLD;
    private javax.swing.JTextField EXPIRATION_FLD;
    private javax.swing.JLabel LOGOUT;
    private javax.swing.JLabel LOGOUT1;
    private javax.swing.JLabel LOGOUT2;
    private javax.swing.JLabel LOGOUT3;
    private javax.swing.JLabel LOGOUT4;
    private javax.swing.JLabel LOGOUT5;
    private javax.swing.JLabel LOGOUT6;
    private javax.swing.JLabel LOGOUT7;
    private javax.swing.JTextField NAME_FLD;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
}
